/**
 * Category → Unsplash search keywords for cover/inline images.
 *
 * Each category has 10+ broad, Unsplash-friendly terms so that even with
 * thousands of posts we get varied cover images. The script picks from these
 * using a hash-based offset to spread results across the pool.
 *
 * Keep terms general enough to return 50+ Unsplash landscape photos each.
 */

export const CATEGORY_IMAGE_KEYWORDS: Record<string, string[]> = {
  'mobile-app-development': [
    'mobile app interface',
    'smartphone technology',
    'mobile application design',
    'person using smartphone',
    'app development team',
    'phone screen closeup',
    'mobile user experience',
    'digital mobile device',
    'mobile notification',
    'tablet and phone workspace',
    'ios android development',
    'mobile wireframe prototype',
  ],
  'mvp-startup': [
    'startup team working',
    'business launch meeting',
    'entrepreneurship office',
    'startup whiteboard brainstorm',
    'coworking space startup',
    'venture capital pitch',
    'product prototype',
    'lean startup workspace',
    'founder working laptop',
    'innovation lab',
    'business plan strategy',
    'early stage company',
  ],
  'ai-solutions': [
    'artificial intelligence technology',
    'machine learning data',
    'neural network visualization',
    'robot automation',
    'AI processor chip',
    'deep learning research',
    'data science analytics',
    'computer vision technology',
    'natural language processing',
    'intelligent automation',
    'futuristic technology',
    'algorithm visualization',
  ],
  'web-app-development': [
    'web development code',
    'programming laptop screen',
    'software developer workspace',
    'code editor screen',
    'responsive web design',
    'developer team collaboration',
    'javascript code screen',
    'modern web application',
    'full stack development',
    'API integration technology',
    'web browser interface',
    'agile development board',
  ],
  'telegram-bot-development': [
    'chatbot conversation interface',
    'messaging app technology',
    'chat automation bot',
    'instant messaging platform',
    'conversational AI interface',
    'notification system technology',
    'social media automation',
    'digital communication tool',
    'bot workflow automation',
    'messaging notification phone',
    'customer service chat',
    'automated response system',
  ],
  'crm-development': [
    'business software dashboard',
    'customer relationship management',
    'sales pipeline analytics',
    'business data management',
    'client database system',
    'contact management software',
    'sales team meeting',
    'customer analytics dashboard',
    'enterprise software screen',
    'business process management',
    'lead management funnel',
    'office team collaboration',
  ],
  'business-automation': [
    'workflow automation technology',
    'business process digital',
    'digital transformation office',
    'automated system dashboard',
    'robotic process automation',
    'efficiency technology business',
    'smart office automation',
    'paperless digital workflow',
    'business intelligence dashboard',
    'operations management system',
    'streamlined business process',
    'enterprise automation',
  ],
  'saas-development': [
    'cloud computing infrastructure',
    'software as a service',
    'cloud platform dashboard',
    'subscription software model',
    'server infrastructure cloud',
    'multi-tenant architecture',
    'cloud data center',
    'scalable web platform',
    'cloud storage technology',
    'platform interface design',
    'microservices architecture',
    'cloud deployment pipeline',
  ],
  outsourcing: [
    'remote team collaboration',
    'global workforce distributed',
    'international business meeting',
    'video conference remote work',
    'offshore development team',
    'freelancer working laptop',
    'distributed team timezone',
    'virtual office workspace',
    'cross-cultural business team',
    'remote developer coding',
    'outsourcing partnership handshake',
    'global talent network',
  ],
  'project-rescue': [
    'project recovery strategy',
    'crisis management meeting',
    'debugging code developer',
    'fixing broken system',
    'technical debt solution',
    'emergency IT response',
    'software audit review',
    'code review team',
    'system migration upgrade',
    'legacy system modernization',
    'troubleshooting technology problem',
    'project turnaround strategy',
  ],
  ecommerce: [
    'ecommerce online shopping',
    'digital store marketplace',
    'online payment checkout',
    'shopping cart website',
    'retail technology platform',
    'product catalog digital',
    'mobile commerce shopping',
    'warehouse logistics technology',
    'dropshipping business model',
    'customer purchase online',
    'marketplace platform interface',
    'inventory management system',
  ],
  'ui-ux-design': [
    'user interface design prototype',
    'UX research wireframe',
    'creative design studio',
    'figma sketch mockup',
    'design system components',
    'user testing session',
    'color palette typography',
    'interaction design prototype',
    'designer workspace tablet',
    'mobile app mockup',
    'usability testing lab',
    'information architecture diagram',
  ],
  'maintenance-support': [
    'technical support helpdesk',
    'server maintenance operations',
    'IT infrastructure monitoring',
    'system update deployment',
    'DevOps monitoring dashboard',
    'network administration server',
    'backup recovery system',
    'uptime monitoring screen',
    'IT service desk support',
    'software patch update',
    'performance optimization server',
    'incident response management',
  ],
  cybersecurity: [
    'cybersecurity protection shield',
    'data encryption security',
    'network security firewall',
    'information security lock',
    'hacker prevention technology',
    'secure authentication login',
    'privacy data protection',
    'penetration testing security',
    'security operations center',
    'encrypted communication network',
    'vulnerability assessment scan',
    'zero trust architecture',
  ],
};

/** Final fallback terms if nothing else works — always returns Unsplash results. */
export const GENERIC_FALLBACK_KEYWORDS = [
  'business technology office',
  'modern software development',
  'digital innovation workspace',
  'technology team collaboration',
  'professional business meeting',
  'computer programming screen',
  'data analytics dashboard',
  'cloud technology network',
];
